name: action_process_text
description: A Flutter plugin for ACTION_PROCESS_TEXT implementation in Android.
version: 2.0.0
repository: https://github.com/coder-with-a-bushido/ACTION_PROCESS_TEXT-Flutter

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.action_process_text
        pluginClass: ActionProcessTextPlugin
